apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-workspace
spec:
  storageClassName: nfs-client-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-war
spec:
  storageClassName: nfs-client-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi