apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    name: jenkins-master
  type: NodePort
  ports:
    - name: http8080
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30088
    - name: agent50000
      port: 50000
      targetPort: 50000
      protocol: TCP
      nodePort: 30089






