apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hx-chat-action-server-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: nfs-client-retain



