apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: name-suffix-transformer
suffix: -dev-1
fieldSpecs:
  - path: metadata/name
    kind: Deployment
  - path: metadata/name
    kind: ConfigMap
  - path: metadata/name
    kind: Service
  - path: metadata/name
    kind: PersistentVolumeClaim