apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins-devops

labels:
  - pairs:
      create-time: 2024-10-21
      owner: colin
      version: 20241021-v0.0.1

replicas:
- name: jenkins-master
  count: 1

images:
- name: jenkins
  newName: jenkins/jenkins
  newTag: lts-jdk17

resources:
  - ../../base
  - persistentvolumeclaim.yaml

configMapGenerator:
- name: nerdctl-configmap
  files:
  - nerdctl.toml
  options:
    disableNameSuffixHash: true
- name: buildkitd-configmap
  files:
  - buildkitd.toml
  options:
    disableNameSuffixHash: true

patches:
  - path: change-pvc.patch.yaml

transformers:
- ./kustomizeconfig/namesuffix-transformer.yaml