kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-agent-workspace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi